version = 0.1

[default.global.parameters]
stack_name = "pdf_process"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "/Users/abenezernuro/projects/Expos/rws_cms/pdf-processor-service/sam/pdf-processor-lambda/template.yaml"
dependency_layer = true
code = true
skip_deploy_sync = true
use_container = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
